# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/darlan/CBIRproject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/darlan/CBIRproject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/darlan/CBIRproject/CMakeFiles /home/darlan/CBIRproject/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/darlan/CBIRproject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projeto

# Build rule for target.
projeto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 projeto
.PHONY : projeto

# fast build rule for target.
projeto/fast:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/build
.PHONY : projeto/fast

helper.o: helper.cpp.o
.PHONY : helper.o

# target to build an object file
helper.cpp.o:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/helper.cpp.o
.PHONY : helper.cpp.o

helper.i: helper.cpp.i
.PHONY : helper.i

# target to preprocess a source file
helper.cpp.i:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/helper.cpp.i
.PHONY : helper.cpp.i

helper.s: helper.cpp.s
.PHONY : helper.s

# target to generate assembly for a file
helper.cpp.s:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/helper.cpp.s
.PHONY : helper.cpp.s

lbp.o: lbp.cpp.o
.PHONY : lbp.o

# target to build an object file
lbp.cpp.o:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/lbp.cpp.o
.PHONY : lbp.cpp.o

lbp.i: lbp.cpp.i
.PHONY : lbp.i

# target to preprocess a source file
lbp.cpp.i:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/lbp.cpp.i
.PHONY : lbp.cpp.i

lbp.s: lbp.cpp.s
.PHONY : lbp.s

# target to generate assembly for a file
lbp.cpp.s:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/lbp.cpp.s
.PHONY : lbp.cpp.s

projeto.o: projeto.cpp.o
.PHONY : projeto.o

# target to build an object file
projeto.cpp.o:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/projeto.cpp.o
.PHONY : projeto.cpp.o

projeto.i: projeto.cpp.i
.PHONY : projeto.i

# target to preprocess a source file
projeto.cpp.i:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/projeto.cpp.i
.PHONY : projeto.cpp.i

projeto.s: projeto.cpp.s
.PHONY : projeto.s

# target to generate assembly for a file
projeto.cpp.s:
	$(MAKE) -f CMakeFiles/projeto.dir/build.make CMakeFiles/projeto.dir/projeto.cpp.s
.PHONY : projeto.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... projeto"
	@echo "... rebuild_cache"
	@echo "... helper.o"
	@echo "... helper.i"
	@echo "... helper.s"
	@echo "... lbp.o"
	@echo "... lbp.i"
	@echo "... lbp.s"
	@echo "... projeto.o"
	@echo "... projeto.i"
	@echo "... projeto.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

